#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate
pip uninstall -y django-stables || echo 'django-stables not available'
